POST https://deriv-navigator.onrender.com/signup
Content-Type: application/json

{
  "first_name": "Alex",
  "account": "alex",
  "email": "alex.gmail.com",
  "phone_no": "254704573938",
  "password": "farbean"
}

POST https://deriv-navigator.onrender.com//login
Content-Type: application/json

{
  "email": "navigator@gmail.com.com",
  "password": "navigator"
}

DELETE https://deriv-navigator.onrender.com//delete/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMDY3NzA0MiwianRpIjoiYmQ2ODliOWUtNDQwZi00ZmZmLWFhNWQtMmQyZWI2ZmZkYWVjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzEwNjc3MDQyLCJjc3JmIjoiNTFjNzUxOTgtY2Q4Zi00Njc5LWJjYjYtYmI2ZmIyN2RjNzE4IiwiZXhwIjoxNzEwNjgwNjQyLCJhZG1pbiI6dHJ1ZX0.gYLGRmjRRR1dE55e0gUOv02TUGhILXTxytr4ojHAzlI

POST https://deriv-navigator.onrender.com//lipa_na_mpesa
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMDk3NDA4MSwianRpIjoiMjRiODY2MDgtNGMxNi00MzAwLTg3ZjEtMTIxMzhlODIxMzk4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzEwOTc0MDgxLCJjc3JmIjoiMmRjZTg5YjYtOTIyMS00YjgzLThhYjgtNTc3NDFiMTM5OWQ1IiwiZXhwIjoxNzEwOTc3NjgxLCJhZG1pbiI6dHJ1ZSwicGhvbmVfbnVtYmVyIjoyNTQ3MDAwMDAwMH0.gAZBk2sHsQAJoaM6XRg2cqoZLoVlN0Wal8Bd9Ouwm5A

{
  "amount": 100
}
